/* 
 * File:   enums.h
 * Author: Frillip
 *
 * Created on 13 April 2024, 19:33
 */

#ifndef SERIAL_PROTO_H
#define	SERIAL_PROTO_H

#ifdef	__cplusplus
extern "C" {
#endif

#define SERIAL_PROTO_STRING_BUFFER_SIZE 100
#define SERIAL_PROTO_CHECK_BUFFER_SIZE 3

#define SERIAL_PROTO_HEADER 0x83
#define SERIAL_PROTO_TYPE_ESP_TX 0x65
#define SERIAL_PROTO_TYPE_PIC_TX 0x70
#define SERIAL_PROTO_DATATYPE_TIMEDATA 0x00
#define SERIAL_PROTO_DATATYPE_GNSSDATA 0x10
#define SERIAL_PROTO_DATATYPE_OFFSETDATA 0x20
#define SERIAL_PROTO_DATATYPE_NETDATA 0x30
#define SERIAL_PROTO_DATATYPE_RTCDATA 0x40
#define SERIAL_PROTO_DATATYPE_SENSORDATA 0x50
#define SERIAL_PROTO_DATATYPE_DISPLAYDATA 0x60
#define SERIAL_PROTO_DATATYPE_MISCDATA 0x70
#define SERIAL_PROTO_DATATYPE_USERDATA 0x80

#define SERIAL_PROTO_ESP_TIME_LENGTH 11
#define SERIAL_PROTO_ESP_GNSS_LENGTH 12
#define SERIAL_PROTO_ESP_OFFSET_LENGTH 20
#define SERIAL_PROTO_ESP_NET_LENGTH 11
#define SERIAL_PROTO_ESP_RTC_LENGTH 7
#define SERIAL_PROTO_ESP_SENSOR_LENGTH 11
#define SERIAL_PROTO_ESP_DISPLAY_LENGTH 7
#define SERIAL_PROTO_ESP_USER_LENGTH 4

#define SERIAL_PROTO_PIC_TIME_LENGTH 10
#define SERIAL_PROTO_PIC_GNSS_LENGTH 12
#define SERIAL_PROTO_PIC_OFFSET_LENGTH 28
#define SERIAL_PROTO_PIC_NET_LENGTH 11
#define SERIAL_PROTO_PIC_RTC_LENGTH 8
#define SERIAL_PROTO_PIC_SENSOR_LENGTH 12
#define SERIAL_PROTO_PIC_DISPLAY_LENGTH 10
#define SERIAL_PROTO_PIC_USER_LENGTH 4

#ifdef	__cplusplus
}
#endif

#endif	/* ENUMS_H */

